            var full_sponsor_list = ['Vodafone Foundation', 'World Vision', 'Fraternidad sin Fonteras', 'DRI',
                'Ambassade des Pays-Bas', 'GFMER', 'Birth Injury Fund', 'WorldShare Australia',
                'Friends of Chilonga', 'Association for the Re-orientation and Rehabilitation of Teso Women for Development',
                'Rotary International', 'Muli Shani Foundation', 'ALDIPE-ONG',
                'European Union', 'OneByOne', 'OGRA Foudnation', 'LAMb International Fund',
                'Women Association', "Women's Rehabilitation Center", 'Society for International Mission',
                'WAHA', 'AMREF', 'WFP', 'Vodacom Foundation', 'Safaricom Foundation',
                'International Association for Maternal and Neonatal Health (Mali)', 'ALLAALE Hospital',
                'Dutch Bangla Bank', 'Women Doctors Association Kano', 'Kupona Foundation',
                'Borama community', 'MGD', 'ISOPF', 'CURE International', 'CBM',
                'Lagos accuill', 'MTN', 'Gloag Foundation', 'Catholic Organization for Relief and Development Aid',
                'ONG SAOUDIENNE', 'Dr Christine Dewind Maria', 'FF', 'Small World', 'J&J',
                'Verona Fathers', 'Good Samaritan Fund', "Pakistan National Forum on Women's Health",
                'AmeriCares', 'University College London', 'GRAEDHI-ONG', 'FfFF', 'mediplast', 'UNDP',
                'AusHeal', 'Equilibres & Populations', 'Zonta International', 'Maternal Health Task Force',
                'Ethiopia Aid', 'Sant Joan de D\xc3\xa9u', 'Doctors with Africa Cuamm',
                'Neukirchen Mission e.V. (Germany)', "Poor People's Fund",
                'ONG TURQUE', "Women's Hope International", 'New Day Foundation', 'Other',
                'MSF', 'WorldVenture', 'Association of Baptists for World Evangelism', 'Friends of Mandritsara Trust',
                'The Gay and Keith Talbot Trust', 'Engender', 'Doctors of the World',
                "Women's Health International", 'UNFPA', 'UKIF', 'Prof.Dr Jacques Kalume',
                'Service to Humanity Katsina', 'International Organization for Women and Development',
                'MATA FRANCE', 'Comprehensive Community Based Rehabilitation in Tanzania (Kilimanjaro)',
                'KOICA', 'Medics Without Vacation', 'Ziekenhuisgroep Twente (Netherlands)',
                'Fauji Foundation Pakistan', 'HEAL Canada', 'GETCO Telecommunications Ltd.',
                'African Mission Healthcare Foundation', 'Innerwheel (Rotary)',
                'M\xc3\xa9decins du desert'];
            major_sponsor = ['-','FF','UNFPA','Engender','AMREF','WAHA','MSF','DRI',
                'FfFF','OneByOne','CBM','GFMER','Other']